name: shopware_sdk
description: Dart SDK for the Shopware 5 REST API.
version: 0.1.0+2
homepage: https://github.com/erkineren/shopware_sdk
author: Erkin Eren <eren@erkin.net>

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  http: ^0.12.0+2