name: shopware_sdk
version: 0.1.0+10
author: Erkin Eren <eren@erkin.net>
homepage: https://github.com/erkineren/shopware_sdk
repository: https://github.com/erkineren/shopware_sdk
description: >-
  A composable, cross-platform, Future-based Dart SDK for the Shopware 5 REST API.


environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  http: ^0.12.0+2