name: shopware_sdk
description: Dart SDK for the Shopware 5 REST API.
version: 0.1.0
homepage: https://github.com/marcoesposito1988/http_auth
author: Erkin Eren <eren@erkin.net>

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  http: ^0.12.0+2